# TODO: finish this script.
version: '3.1'

services:
  console:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8090:80"
    volumes:
      - ./config.ini:/usr/share/nginx/html/config.ini
      - ./certificates:/etc/certificates
    command: /bin/bash -c "nginx -g 'daemon off;'"
    networks:
      - backend
networks:
  backend:
    driver: bridge
