# TODO: finish this script.
version: '3.1'

services:
  console:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9080:80"
      - "9443:443"
    volumes:
      - ./config.ini:/usr/share/nginx/html/config.ini
      - ./certificates:/etc/certificates
    environment:
      - NGINX_HOST=localhost
    command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - backend
networks:
  backend:
    driver: bridge
